name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test1
      id: test1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test1
        setup-command: g++ Test1.cpp -o test1
        command: "./test1"
        input: ''
        expected-output: 'The interleaved array is: 12 1 2 24 2 22 6 3 11 8 4 2 24
          5 16 16 1 11 9 2 13 6 12 7 17 16 22 17 9 18'
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test2
      id: test2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test2
        setup-command: g++ Test2.cpp -o test2
        command: "./test2"
        input: ''
        expected-output: 'The interleaved array is: 23 9 2 52 10 22 16 42 89 15'
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test3
      id: test3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test3
        setup-command: g++ Test3.cpp -o test3
        command: "./test3"
        input: ''
        expected-output: 'The interleaved array is: 5 2 3 10 4 6 6 9 12'
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Test4
      id: test4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test4
        setup-command: g++ Test4.cpp -o test4
        command: "./test4"
        input: ''
        expected-output: 'The interleaved array is: 1 2 3 4 5 6'
        comparison-method: contains
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST1_RESULTS: "${{steps.test1.outputs.result}}"
        TEST2_RESULTS: "${{steps.test2.outputs.result}}"
        TEST3_RESULTS: "${{steps.test3.outputs.result}}"
        TEST4_RESULTS: "${{steps.test4.outputs.result}}"
      with:
        runners: test1,test2,test3,test4
